const user = {
    id: 1,
    name: "Dylan",
    email: "dylan@gmail.com",
    password: "123456",
    phone: "96969696",
};

const goals = [
    {
        id: 1,
        name: "Transport",
        targetAmount: 500,
        targetDate: "2026-01-31",
        status: "active",
        goalType: "expense",
    },
    {
        id: 2,
        name: "Food & Dining",
        targetAmount: 300,
        targetDate: "2026-01-31",
        status: "active",
        goalType: "expense",
    },
    {
        id: 3,
        name: "Vacation",
        targetAmount: 2000,
        targetDate: "2026-12-31",
        status: "active",
        goalType: "expense",
    },
    {
        id: 4,
        name: "Emergency Fund",
        targetAmount: 5000,
        targetDate: "2026-12-31",
        status: "active",
        goalType: "income",
    },
    {
        id: 5,
        name: "Electronics",
        targetAmount: 1200,
        targetDate: "2025-12-31",
        status: "completed",
        completedDate: "2025-12-31",
        goalType: "expense",
    },
    {
        id: 6,
        name: "Shopping",
        targetAmount: 800,
        targetDate: "2025-12-31",
        status: "completed",
        completedDate: "2025-11-30",
        goalType: "expense",
    },
    {
        id: 7,
        name: "Dividend",
        targetAmount: 1000,
        targetDate: "2026-01-01",
        status: "active",
        goalType: "income",
    }
];

const transactions = [
    {
        id: 1,
        description: "Transport to work",
        amount: -50.00,
        category: "Transport",
        date: "2026-01-02",
        paymentMethod: "Bank Transfer",
        type: "expense",
    },
    {
        id: 2,
        description: "Grab Ride",
        amount: -15.00,
        category: "Transport",
        date: "2026-01-01",
        paymentMethod: "Credit Card",
        type: "expense",
    },
    {
        id: 3,
        description: "Grocery Shopping",
        amount: -100.00,
        category: "Shopping",
        date: "2026-01-02",
        paymentMethod: "Credit Card",
        type: "expense",
    },
    {
        id: 4,
        description: "Dinner at Restaurant",
        amount: -60.00,
        category: "Food & Dining",
        date: "2026-01-03",
        paymentMethod: "Credit Card",
        type: "expense",
    },
    {
        id: 5,
        description: "McDonald's",
        amount: -20.00,
        category: "Food & Dining",
        date: "2026-01-04",
        paymentMethod: "E-Wallet",
        type: "expense",
    },
    {
        id: 6,
        description: "Salary for December",
        amount: 4500.00,
        category: "Salary",
        date: "2026-01-02",
        paymentMethod: "Bank Transfer",
        type: "income",
    },
    {
        id: 7,
        description: "Freelance Project",
        amount: 800.00,
        category: "Freelance",
        date: "2026-01-13",
        paymentMethod: "Bank Transfer",
        type: "income",
    },
    {
        id: 8,
        description: "Grocery Shopping",
        amount: -120.50,
        category: "Shopping",
        date: "2026-01-13",
        paymentMethod: "E-Wallet",
        type: "expense",
    },
    {
        id: 9,
        description: "Netflix Subscription",
        amount: -15.00,
        category: "Entertainment",
        date: "2026-01-07",
        paymentMethod: "Credit Card",
        type: "expense",
    },
    {
        id: 10,
        description: "Electricity Bill",
        amount: -75.25,
        category: "Bills & Utilities",
        date: "2026-01-08",
        paymentMethod: "Bank Transfer",
        type: "expense",
    },
    {
        id: 11,
        description: "Movie Night",
        amount: -30.00,
        category: "Entertainment",
        date: "2026-01-09",
        paymentMethod: "Credit Card",
        type: "expense",
    },
    {
        id: 12,
        description: "Online Course",
        amount: -100.00,
        category: "Education",
        date: "2026-01-10",
        paymentMethod: "Credit Card",
        type: "expense",
    },
    {
        id: 13,
        description: "Flight Tickets",
        amount: -600.00,
        category: "Vacation",
        date: "2026-01-11",
        paymentMethod: "Credit Card",
        type: "expense",
    },
    {
        id: 14,
        description: "Hotel Booking",
        amount: -800.00,
        category: "Vacation",
        date: "2026-01-12",
        paymentMethod: "Credit Card",
        type: "expense",
    },
    {
        id: 15,
        description: "Shopee",
        amount: -200.00,
        category: "Shopping",
        date: "2026-01-15",
        paymentMethod: "E-Wallet",
        type: "expense",
    }
];

module.exports = {
    user,
    goals,
    transactions,
}